name: Build APK with kivy/buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK using Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app kivy/buildozer \
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: loginapp-debug.apk
          path: bin/*.apk

